### ISSUE TITLE
Cannot handle messages

### ISSUE THREAD

**Issue by austinhuang0131** [Wolke/botbuilder-linebot-connector#2]
```
2017-11-03T01:31:40.557744+00:00 app[web.1]: TypeError: _this.handler is not a function
2017-11-03T01:31:40.557745+00:00 app[web.1]:     at /app/node_modules/botbuilder-linebot-connector/dist/LineConnector.js:230:23
2017-11-03T01:31:40.557745+00:00 app[web.1]:     at Array.forEach (native)
2017-11-03T01:31:40.557746+00:00 app[web.1]:     at LineConnector.dispatch (/app/node_modules/botbuilder-linebot-connector/dist/LineConnector.js:164:21)
2017-11-03T01:31:40.557749+00:00 app[web.1]:     at /app/node_modules/botbuilder-linebot-connector/dist/LineConnector.js:251:23
2017-11-03T01:31:40.557749+00:00 app[web.1]:     at /app/node_modules/body-parser/lib/read.js:130:5
2017-11-03T01:31:40.557750+00:00 app[web.1]:     at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
2017-11-03T01:31:40.557750+00:00 app[web.1]:     at done (/app/node_modules/raw-body/index.js:213:7)
2017-11-03T01:31:40.557751+00:00 app[web.1]:     at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
2017-11-03T01:31:40.557751+00:00 app[web.1]:     at emitNone (events.js:86:13)
2017-11-03T01:31:40.557751+00:00 app[web.1]:     at IncomingMessage.emit (events.js:185:7)
```

**Comment by Wolke** [comment]
I change this to version 2
